### ISSUE TITLE
No such file or directory: [ROOT]/data/scene_changes.log

### ISSUE THREAD

**Issue by anne-o-pixel** [Ryu1845/YoloCR#9] opened 2021-06-27 20:53 UTC
Hello

After #8, I switch to `znedi3` for up-scaling, but now I have this error when running `vspipe -y YoloCR.py - | ffmpeg -i - -c:v mpeg4 -qscale:v 3 -y name_of_the_video_output.mp4`

```
Script evaluation failed:
Python exception: [Errno 2] No such file or directory: '[ROOT]/data/scene_changes.log'

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2244, in vapoursynth.vpy_evaluateScript
  File "src\cython\vapoursynth.pyx", line 2245, in vapoursynth.vpy_evaluateScript
  File "YoloCR.py", line 369, in <module>
    yolocr.main()
  File "YoloCR.py", line 308, in main
    with open(ROOT + "/data/scene_changes.log", "w") as log_io:
FileNotFoundError: [Errno 2] No such file or directory: '[ROOT]/data/scene_changes.log'
```

And it's true that I don't have any `data` folder in my directory, nor any `scene_changes.log`.

I can create a `data` folder but how can I populate the `scene_changes.log` file?

**Comment by Ryu1845** [comment] 2021-06-27 21:37
just creating the folder should work, the error is because it's trying to create the file in a directory which doesn't exist
I fixed the problem in the commit mentioned

**Comment by anne-o-pixel** [comment] 2021-06-27 21:42
thanks

**Comment by anne-o-pixel** [comment] 2021-06-27 21:58
I have your changes but in the case that the folder `data` does not exist, it's failing in the same way than before

**Comment by Ryu1845** [comment] 2021-06-27 22:59
I think I'll just create a file in that folder so git saves it

**Comment by Ryu1845** [comment] 2021-06-27 23:04
there shouldn't be any problem as of https://github.com/Ryu1845/YoloCR/commit/3909009fdbe6825faee588945c215e67b5d608e5
I'll close this tomorrow if the problem is solved

**Closed as completed** 2021-06-29 13:11 UTC
